### PR TITLE
Switch to factory pattern

### PR DESCRIPTION
**Pull request by emirotin**
standardize package.json
work properly with the new resin-request
update dev dependencies
add browser tests
replace nock with fetch-mock
use granular lodash imports
use recent api version

### CODE REVIEW

**Comment by emirotin** [comment]
Huh. The resin-request module relies on the `qs` module that is not in its package.json. But it works on Node 6 because it seems to be installed by some peer dep. Will fix it there.

**Comment by emirotin** [comment]
OK @jviotti it's fixed now. BTW Appveyor is not running for this repo, can you check why?

**Comment by jviotti** [comment]
Weird. The Appveyor dashboard shows that its enabled. I've disabled and enabled again. Can you try triggering a new build now?

**Comment by emirotin** [comment]
Yes, worked now. Good to merge?

**Comment by jviotti** [comment]
:+1:

**Pull request merged**
